using Monkey.Lexing;
using Monkey.Parsing.Nodes;

namespace Monkey.Parsing;

/// <summary>
/// Represents a parser that parses the tokens generated by the Lexer.
/// </summary>
public class Parser
{
    private readonly List<string> _errors = [];
    private readonly Dictionary<string, Func<Node>> _prefixFunctions = new();
    private readonly Dictionary<string, Func<Node, Node>> _infixFunctions = new();

    /// <summary>
    /// Creates a parser that reads its tokens from the given lexer.
    /// </summary>
    public Parser(Lexer lexer)
    {
        Lexer = lexer;

        RegisterParserFunctions();

        Consume();
        Consume();
    }

    public IEnumerable<string> Errors => _errors;

    public bool HasErrors => _errors.Count > 0;

    private Lexer Lexer { get; }

    private Token CurrentToken { get; set; } = Token.Null;

    private Token PeekToken { get; set; } = Token.Null;

    public ProgramNode ParseProgram()
    {
        var programme = ProgramNode.Create();

        while (!CurrentToken.Is(Token.Eof))
        {
            var statement = ParseStatement();

            if (statement != Node.Null)
            {
                programme.Statements.Add(statement);
            }

            Consume();
        }

        return programme;
    }

    #region private methods

    #region registry

    private void RegisterParserFunctions()
    {
        RegisterPrefix(Token.Identifier,
            () => new IdentifierNode(CurrentToken, CurrentToken.Literal));

        RegisterPrefix(Token.Int,
            () => new IntegerNode(CurrentToken, int.Parse(CurrentToken.Literal)));

        RegisterPrefix(Token.True,
            () => new BooleanNode(CurrentToken, CurrentToken.Is(Token.True)));

        RegisterPrefix(Token.False,
            () => new BooleanNode(CurrentToken, CurrentToken.Is(Token.True)));

        RegisterPrefix(Token.String,
            () => new StringNode(CurrentToken, CurrentToken.Literal));

        RegisterPrefix(Token.Bang, ParsePrefixExpression);
        RegisterPrefix(Token.Minus, ParsePrefixExpression);
        RegisterPrefix(Token.LParen, ParseGroupedExpression);
        RegisterPrefix(Token.If, ParseIfExpression);
        RegisterPrefix(Token.Function, ParseFunctionExpression);
        RegisterPrefix(Token.LBracket, ParseArrayLiteral);
        RegisterPrefix(Token.LBrace, ParseHashLiteral);

        RegisterInfix(Token.Plus, ParseInfixExpression);
        RegisterInfix(Token.Minus, ParseInfixExpression);
        RegisterInfix(Token.Slash, ParseInfixExpression);
        RegisterInfix(Token.Asterisk, ParseInfixExpression);
        RegisterInfix(Token.Eq, ParseInfixExpression);
        RegisterInfix(Token.NotEq, ParseInfixExpression);
        RegisterInfix(Token.Lt, ParseInfixExpression);
        RegisterInfix(Token.Gt, ParseInfixExpression);
        RegisterInfix(Token.LParen, ParseCallExpression);
        RegisterInfix(Token.LBracket, ParseIndexExpression);
    }

    private void RegisterPrefix(string type, Func<Node> fn)
        => _prefixFunctions[type] = fn;

    private void RegisterInfix(string type, Func<Node, Node> fn)
        => _infixFunctions[type] = fn;

    #endregion

    #region statements

    private Node ParseStatement()
    {
        return CurrentToken.Type switch
        {
            Token.Let => ParseLetStatement(),
            Token.Return => ParseReturnStatement(),
            _ => ParseExpressionStatement()
        };
    }

    private Node ParseLetStatement()
    {
        var statement = new LetNode(CurrentToken);

        Consume(Token.Identifier);

        statement.Name = new IdentifierNode(CurrentToken, CurrentToken.Literal);

        Consume(Token.Assign);

        Consume();

        statement.Value = ParseExpression(Precedence.Lowest);

        if (PeekToken.Is(Token.Semicolon))
        {
            Consume();
        }

        return statement;
    }

    private Node ParseReturnStatement()
    {
        var statement = new ReturnNode(CurrentToken);

        Consume();

        statement.ReturnValue = ParseExpression(Precedence.Lowest);

        if (PeekToken.Is(Token.Semicolon))
        {
            Consume();
        }

        return statement;
    }

    private Node ParseExpressionStatement()
    {
        var statement = new ExpressionNode(CurrentToken, ParseExpression(Precedence.Lowest));

        if (PeekToken.Is(Token.Semicolon))
        {
            Consume();
        }

        return statement;
    }

    private BlockNode ParseBlockStatement()
    {
        var block = new BlockNode(CurrentToken);

        Consume();

        while (!CurrentToken.Is(Token.RBrace) && !CurrentToken.Is(Token.Eof))
        {
            var statement = ParseStatement();

            if (statement != Node.Null)
            {
                block.Statements.Add(statement);
            }

            Consume();
        }

        return block;
    }

    #endregion

    #region expressions

    private Node ParseExpression(Precedence precedence)
    {
        if (!_prefixFunctions.TryGetValue(CurrentToken.Type, out var prefix))
        {
            _errors.Add($"no prefix parse function for {CurrentToken.Type} found");
            return Node.Null;
        }

        var leftExpression = prefix();

        while (!PeekToken.Is(Token.Semicolon) && precedence < Precedences.Resolve(PeekToken.Type))
        {
            if (!_infixFunctions.TryGetValue(PeekToken.Type, out var infix))
            {
                return leftExpression;
            }

            Consume();

            leftExpression = infix(leftExpression);
        }

        return leftExpression;
    }

    // prefix parse functions

    private Node ParsePrefixExpression()
    {
        var expression = new PrefixNode(CurrentToken, CurrentToken.Literal);

        Consume();

        expression.Right = ParseExpression(Precedence.Prefix);

        return expression;
    }

    private Node ParseGroupedExpression()
    {
        Consume();

        var expression = ParseExpression(Precedence.Lowest);

        Consume(Token.RParen);

        return expression;
    }

    private Node ParseIfExpression()
    {
        var expression = new IfNode(CurrentToken);

        Consume(Token.LParen);

        Consume();

        expression.Condition = ParseExpression(Precedence.Lowest);

        Consume(Token.RParen);
        Consume(Token.LBrace);

        expression.Consequence = ParseBlockStatement();

        if (!PeekToken.Is(Token.Else)) return expression;

        Consume();

        Consume(Token.LBrace);

        expression.Alternative = ParseBlockStatement();

        return expression;
    }

    private Node ParseFunctionExpression()
    {
        var expression = new FunctionNode(CurrentToken);

        Consume(Token.LParen);

        expression.Parameters = ParseFunctionParameters();

        Consume(Token.LBrace);

        expression.Body = ParseBlockStatement();

        return expression;
    }

    private List<IdentifierNode> ParseFunctionParameters()
    {
        var identifiers = new List<IdentifierNode>();

        if (PeekToken.Is(Token.RParen))
        {
            Consume();
            return identifiers;
        }

        Consume(Token.Identifier);

        var identifier = new IdentifierNode(token: CurrentToken, value: CurrentToken.Literal);

        identifiers.Add(identifier);

        while (PeekToken.Is(Token.Comma))
        {
            Consume();
            Consume(Token.Identifier);

            identifier = new IdentifierNode(token: CurrentToken, value: CurrentToken.Literal);
            identifiers.Add(identifier);
        }

        Consume(Token.RParen);

        return identifiers;
    }

    private Node ParseArrayLiteral()
        => new ArrayNode(CurrentToken, ParseExpressionList(Token.RBracket));

    private Node ParseHashLiteral()
    {
        var hash = new HashNode(CurrentToken);

        if (PeekToken.Is(Token.RBrace))
        {
            Consume();
            return hash;
        }

        while (!PeekToken.Is(Token.Eof))
        {
            Consume();
            var key = ParseExpression(Precedence.Lowest);

            Consume(Token.Colon);
            Consume();
            var value = ParseExpression(Precedence.Lowest);

            hash.Pairs.Add(key, value);

            if (PeekToken.Is(Token.RBrace))
            {
                Consume();
                return hash;
            }

            if (!PeekToken.Is(Token.Comma)) break;
            Consume();
        }

        throw new ParserException($"expected next token to be {Token.RBrace}, got {PeekToken.Type} instead", PeekToken);
    }

    // infix parse functions

    private Node ParseInfixExpression(Node left)
    {
        var expression = new InfixNode(CurrentToken, CurrentToken.Literal, left);

        var precedence = Precedences.Resolve(CurrentToken.Type);

        Consume();

        expression.Right = ParseExpression(precedence);

        return expression;
    }

    private Node ParseCallExpression(Node function)
        => new CallNode(CurrentToken, function, ParseExpressionList(Token.RParen));

    private Node ParseIndexExpression(Node left)
    {
        var expression = new IndexNode(CurrentToken, left);

        Consume();

        expression.Index = ParseExpression(Precedence.Lowest);

        Consume(Token.RBracket);

        return expression;
    }

    private List<Node> ParseExpressionList(string end)
    {
        var list = new List<Node>();

        if (PeekToken.Is(end))
        {
            Consume();
            return list;
        }

        Consume();
        list.Add(ParseExpression(Precedence.Lowest));

        while (PeekToken.Is(Token.Comma))
        {
            Consume();
            Consume();
            list.Add(ParseExpression(Precedence.Lowest));
        }

        Consume(end);

        return list;
    }

    #endregion

    #region token handling

    private void Consume()
    {
        CurrentToken = PeekToken;
        PeekToken = Lexer.NextToken();
    }

    private void Consume(string type)
    {
        if (PeekToken.Is(type))
        {
            Consume();
            return;
        }

        throw new ParserException($"expected next token to be {type}, got {PeekToken.Type} instead", PeekToken);
    }

    #endregion

    #endregion
}
