using Monkey.Lexing;
using Monkey.Parsing.Nodes;
using Monkey.Utils;

namespace Monkey.Parsing;

/// <summary>
/// Represents a parser that parses the tokens generated by the Lexer.
/// </summary>
public partial class Parser
{
    /// <summary
    public Parser(Lexer lexer)
    {
        Lexer = lexer;

        RegisterParserFunctions();
        
        Consume();
        Consume();
    }
    
    private Lexer Lexer { get; }

    private Token CurrentToken { get; set; } = Token.Null;

    private Token PeekToken { get; set; } = Token.Null;
    
    private Node ParseHashLiteral()
    {
        var hash = new HashNode(CurrentToken);
        
        if (PeekToken.Is(Token.RBrace))
        {
            Consume();
            return hash;
        }
        
        while (!PeekToken.Is(Token.Eof)) 
        {
            Consume();
            var key = ParseExpression(Precedence.Lowest);
            
            Consume(Token.Colon);
            Consume();
            var value = ParseExpression(Precedence.Lowest);
            
            hash.Pairs.Add(key, value);

            if (PeekToken.Is(Token.RBrace))
            {
                Consume();
                return hash;
            }

            if (!PeekToken.Is(Token.Comma)) break;
            Consume();
        }
        
        throw Fatal.Error($"expected next token to be {Token.RBrace}, got {PeekToken.Type} instead");
    }

    private Node ParseIndexExpression(Node left)
    {
        var expression = new IndexNode(CurrentToken, left);
        
        Consume();
        
        expression.Index = ParseExpression(Precedence.Lowest);

        Consume(Token.RBracket);
        
        return expression;
    }

    private Node ParseArrayLiteral()
        => new ArrayNode(CurrentToken, ParseExpressionList(Token.RBracket));

    private List<Node> ParseExpressionList(string end)
    {
        var list = new List<Node>();
        
        if (PeekToken.Is(end))
        {
            Consume();
            return list;
        }
        
        Consume();
        list.Add(ParseExpression(Precedence.Lowest));
        
        while (PeekToken.Is(Token.Comma))
        {
            Consume();
            Consume();
            list.Add(ParseExpression(Precedence.Lowest));
        }

        Consume(end);

        return list;
    }

    private Node ParseCallExpression(Node function)
        => new CallNode(CurrentToken, function, ParseExpressionList(Token.RParen));
    
    private Node ParseFunctionExpression()
    {
        var expression = new FunctionNode(CurrentToken);
        
        Consume(Token.LParen);
        
        expression.Parameters = ParseFunctionParameters();
        
        Consume(Token.LBrace);
        
        expression.Body = ParseBlockStatement();
        
        return expression;    
    }
    
    private List<IdentifierNode> ParseFunctionParameters()
    {
        var identifiers = new List<IdentifierNode>();
        
        if (PeekToken.Is(Token.RParen))
        {
            Consume();
            return identifiers;
        }
        
        Consume();
        
        var identifier = new IdentifierNode(token: CurrentToken, value: CurrentToken.Literal);
        
        identifiers.Add(identifier);
        
        while (PeekToken.Is(Token.Comma))
        {
            Consume();
            Consume();
            
            identifier = new IdentifierNode(token: CurrentToken, value: CurrentToken.Literal);
            identifiers.Add(identifier);
        }
        
        Consume(Token.RParen);
        
        return identifiers;
    }
    
    private Node ParsePrefixExpression()
    {
        var expression = new PrefixNode(CurrentToken, CurrentToken.Literal);
        
        Consume();
        
        expression.Right = ParseExpression(Precedence.Prefix);
        
        return expression;
    }
    
    private Node ParseInfixExpression(Node left)
    {
        var expression = new InfixNode(CurrentToken, CurrentToken.Literal, left);

        var precedence = Precedences.Resolve(CurrentToken.Type);
        
        Consume();
        
        expression.Right = ParseExpression(precedence);
        
        return expression;
    }
    
    private Node ParseGroupedExpression()
    {
        Consume();
        
        var expression = ParseExpression(Precedence.Lowest);
        
        Consume(Token.RParen);
        
        return expression;
    }
    
    private Node ParseIfExpression()
    {
        var expression = new IfNode(CurrentToken);

        Consume(Token.LParen);
        
        Consume();
        
        expression.Condition = ParseExpression(Precedence.Lowest);
        
        Consume(Token.RParen);
        Consume(Token.LBrace);
        
        expression.Consequence = ParseBlockStatement();

        if (!PeekToken.Is(Token.Else)) return expression;
        
        Consume();
            
        Consume(Token.LBrace);
            
        expression.Alternative = ParseBlockStatement();

        return expression;
    }
    
    private BlockNode ParseBlockStatement()
    {
        var block = new BlockNode(CurrentToken);
        
        Consume();
        
        while (!CurrentToken.Is(Token.RBrace) && !CurrentToken.Is(Token.Eof))
        {
            var statement = ParseStatement();
            
            // should we exit if null?
            if (statement != Node.Null)
            {
                block.Statements.Add(statement);
            }
            
            Consume();
        }
        
        return block;
    }
    
    public ProgramNode ParseProgramme()
    {
        var programme = ProgramNode.Create();
        
        while (!CurrentToken.Is(Token.Eof))
        {
            var statement = ParseStatement();
            
            // should we exit if null?
            if (statement != Node.Null)
            {
                programme.Statements.Add(statement);
            }
            
            Consume();
        }
        
        return programme;
    }

    private Node ParseStatement()
    {
        return CurrentToken.Type switch
        {
            Token.Let => ParseLetStatement(),
            Token.Return => ParseReturnStatement(),
            _ => ParseExpressionStatement()
        };
    }

    private Node ParseExpressionStatement()
    {
        var statement = new ExpressionNode(CurrentToken, ParseExpression(Precedence.Lowest));

        if (PeekToken.Is(Token.Semicolon))
        {
            Consume();
        }

        return statement;
    }

    private Node ParseExpression(Precedence precedence)
    {
        if (!_prefixFunctions.TryGetValue(CurrentToken.Type, out var prefix))
        {
            _errors.Add($"no prefix parse function for {CurrentToken.Type} found");
            return Node.Null;
        }
        
        var leftExpression = prefix();
        
        while (!PeekToken.Is(Token.Semicolon) && precedence < Precedences.Resolve(PeekToken.Type))
        {
            if (!_infixFunctions.TryGetValue(PeekToken.Type, out var infix))
            {
                return leftExpression;
            }
            
            Consume();
            
            leftExpression = infix(leftExpression);
        }
        
        return leftExpression;
    }

    private Node ParseReturnStatement()
    {
        var statement = new ReturnNode(CurrentToken);
        
        Consume();
        
        statement.ReturnValue = ParseExpression(Precedence.Lowest);
        
        if (PeekToken.Is(Token.Semicolon))
        {
            Consume();
        }
        
        return statement;
    }

    private Node ParseLetStatement()
    {
        var statement = new LetNode(CurrentToken);
        
        Consume(Token.Identifier);
        
        statement.Name = new IdentifierNode(CurrentToken, CurrentToken.Literal);

        Consume(Token.Assign);
        
        Consume();

        statement.Value = ParseExpression(Precedence.Lowest);
        
        // todo: shouldn't this be an error if it is not a semicolon?
        if (PeekToken.Is(Token.Semicolon))
        {
            Consume();
        }
        
        return statement;
    }
    
    private void Consume()
    {
        CurrentToken = PeekToken;
        PeekToken = Lexer.NextToken();
    }

    private void Consume(string type)
    {
        if (PeekToken.Is(type))
        {
            Consume();
            return;
        }
        
        throw Fatal.Error($"expected next token to be {type}, got {PeekToken.Type} instead");
    }
}